In [1]:
#load packages
import numpy as np
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import soundfile as sf


In [2]:
#import data 
path = 'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=2.wav')
classes = pd.read_csv(path + 'Classes_2.csv')


In [3]:

X = data[:len(data)-1,:data.shape[1]] #775361
Y = classes.values[:,0]

In [8]:
Y

array([1, 1, 1, ..., 5, 5, 5], dtype=int64)

In [9]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [10]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)

In [11]:
integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY), 1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)


In [12]:
onehot_encoded_train 


array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [13]:
#DC removal 
trainX -= (np.mean(trainX, axis=0) + 1e-8)
testX -= (np.mean(testX, axis=0) + 1e-8)

In [14]:
clf = keras.Sequential()

In [15]:
onehot_encoded_train.shape[1], X.shape[1],onehot_encoded_train


(5, 108, array([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.]]))

In [16]:
clf.add(keras.layers.Dense(
  units = 56,
  input_dim = trainX.shape[1],   
  activation = 'tanh'
))

clf.add(keras.layers.Dense(
    units = onehot_encoded_train.shape[1],
    input_dim = 56,
    activation = 'softmax'
))



In [17]:
onehot_encoded_train.shape[1]

5

In [18]:
clf.compile(loss='mean_squared_error',
    optimizer='Adam',
           metrics=['categorical_accuracy'])

In [19]:
history = clf.fit(trainX,onehot_encoded_train,
                 batch_size = 64, epochs = 150,
                 verbose = 1,
                 validation_split = 0.1)

Train on 763214 samples, validate on 84802 samples
Epoch 1/150
763214/763214 [==============================] - 12s 16us/step - loss: 0.1460 - categorical_accuracy: 0.3961 - val_loss: 0.1407 - val_categorical_accuracy: 0.4363
Epoch 2/150
763214/763214 [==============================] - 10s 13us/step - loss: 0.1388 - categorical_accuracy: 0.4522 - val_loss: 0.1378 - val_categorical_accuracy: 0.4608
Epoch 3/150
763214/763214 [==============================] - 11s 14us/step - loss: 0.1376 - categorical_accuracy: 0.4612 - val_loss: 0.1376 - val_categorical_accuracy: 0.4674
Epoch 4/150
763214/763214 [==============================] - 14s 18us/step - loss: 0.1374 - categorical_accuracy: 0.4631 - val_loss: 0.1373 - val_categorical_accuracy: 0.4622
Epoch 5/150
763214/763214 [==============================] - 13s 16us/step - loss: 0.1370 - categorical_accuracy: 0.4646 - val_loss: 0.1366 - val_categorical_accuracy: 0.4743
Epoch 6/150
763214/763214 [==============================] - 12s 15us/step

763214/763214 [==============================] - 12s 16us/step - loss: 0.0692 - categorical_accuracy: 0.7568 - val_loss: 0.0688 - val_categorical_accuracy: 0.7523
Epoch 48/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0687 - categorical_accuracy: 0.7592 - val_loss: 0.0681 - val_categorical_accuracy: 0.7665
Epoch 49/150
763214/763214 [==============================] - 12s 16us/step - loss: 0.0682 - categorical_accuracy: 0.7617 - val_loss: 0.0679 - val_categorical_accuracy: 0.7581
Epoch 50/150
763214/763214 [==============================] - 14s 19us/step - loss: 0.0677 - categorical_accuracy: 0.7639 - val_loss: 0.0672 - val_categorical_accuracy: 0.7639
Epoch 51/150
763214/763214 [==============================] - 14s 19us/step - loss: 0.0672 - categorical_accuracy: 0.7659 - val_loss: 0.0666 - val_categorical_accuracy: 0.7634
Epoch 52/150
763214/763214 [==============================] - 17s 22us/step - loss: 0.0667 - categorical_accuracy: 0.7681 - val_loss:

763214/763214 [==============================] - 14s 18us/step - loss: 0.0547 - categorical_accuracy: 0.8166 - val_loss: 0.0542 - val_categorical_accuracy: 0.8167
Epoch 94/150
763214/763214 [==============================] - 16s 21us/step - loss: 0.0546 - categorical_accuracy: 0.8173 - val_loss: 0.0546 - val_categorical_accuracy: 0.8255
Epoch 95/150
763214/763214 [==============================] - 14s 18us/step - loss: 0.0544 - categorical_accuracy: 0.8179 - val_loss: 0.0539 - val_categorical_accuracy: 0.8235
Epoch 96/150
763214/763214 [==============================] - 15s 20us/step - loss: 0.0542 - categorical_accuracy: 0.8184 - val_loss: 0.0539 - val_categorical_accuracy: 0.8163
Epoch 97/150
763214/763214 [==============================] - 14s 19us/step - loss: 0.0541 - categorical_accuracy: 0.8190 - val_loss: 0.0537 - val_categorical_accuracy: 0.8231
Epoch 98/150
763214/763214 [==============================] - 16s 21us/step - loss: 0.0539 - categorical_accuracy: 0.8198 - val_loss:

763214/763214 [==============================] - 13s 17us/step - loss: 0.0487 - categorical_accuracy: 0.8383 - val_loss: 0.0484 - val_categorical_accuracy: 0.8407
Epoch 140/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0486 - categorical_accuracy: 0.8387 - val_loss: 0.0483 - val_categorical_accuracy: 0.8431
Epoch 141/150
763214/763214 [==============================] - 13s 16us/step - loss: 0.0485 - categorical_accuracy: 0.8391 - val_loss: 0.0480 - val_categorical_accuracy: 0.8413
Epoch 142/150
763214/763214 [==============================] - 12s 16us/step - loss: 0.0484 - categorical_accuracy: 0.8395 - val_loss: 0.0479 - val_categorical_accuracy: 0.8412
Epoch 143/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0483 - categorical_accuracy: 0.8398 - val_loss: 0.0486 - val_categorical_accuracy: 0.8374
Epoch 144/150
763214/763214 [==============================] - 16s 21us/step - loss: 0.0482 - categorical_accuracy: 0.8400 - val_

In [20]:
clf.predict_classes(testX[1:100,:]) + 1,testY[1:100]

(array([4, 2, 3, 3, 4, 1, 4, 2, 5, 3, 1, 2, 3, 2, 4, 4, 2, 1, 4, 2, 4, 2,
        2, 2, 2, 2, 1, 4, 5, 2, 3, 5, 4, 2, 2, 4, 3, 3, 3, 4, 1, 2, 2, 2,
        1, 4, 2, 3, 5, 4, 4, 2, 2, 4, 4, 3, 5, 1, 4, 3, 1, 5, 2, 2, 3, 5,
        2, 5, 4, 2, 1, 4, 5, 2, 4, 2, 3, 4, 2, 1, 2, 2, 5, 3, 2, 5, 4, 4,
        1, 2, 4, 2, 2, 1, 2, 4, 5, 4, 1], dtype=int64),
 array([4, 4, 3, 3, 2, 1, 4, 2, 5, 3, 4, 2, 3, 2, 5, 4, 2, 1, 5, 2, 4, 2,
        2, 2, 2, 4, 1, 4, 5, 4, 3, 5, 4, 4, 2, 4, 3, 3, 3, 4, 1, 2, 2, 2,
        1, 4, 2, 3, 5, 5, 4, 2, 2, 4, 2, 3, 5, 1, 4, 3, 1, 5, 2, 5, 3, 4,
        2, 4, 4, 2, 1, 4, 4, 4, 4, 2, 3, 4, 2, 1, 2, 2, 5, 3, 4, 5, 2, 4,
        1, 2, 4, 4, 2, 1, 4, 4, 5, 4, 4], dtype=int64))

In [24]:
clf.evaluate(testX,onehot_encoded_test,verbose=1)

212005/212005 [==============================] - 2s 10us/step


[0.04782811622189045, 0.8409141293840221]

In [25]:
# saving the model 
# save model and weights
clf_json = clf.to_json()
with open("NN_108-56-5.json", "w") as json_file:
    json_file.write(clf_json)
    
clf.save_weights("NN_108-56-5_weights.h5")

In [26]:
np.save('TestX_NN_108-56-5',testX), np.save('TestY_NN_108-56-5',testY),
np.save('OneHot_testY_108-56-5',onehot_encoded_test)

In [27]:
trainX.shape

(848016, 108)