In [1]:
#load packages
import numpy as np
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import soundfile as sf


In [2]:
#import data 
path = 'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=2bil_BF.wav')
classes = pd.read_csv(path + 'Classes_2bil_BF.csv')

In [9]:
X = data[:len(data)-1,:data.shape[1]] 
Y = classes.values[:,0]

In [10]:
len(Y),len(X), X.shape

(889913, 889913, (889913, 18))

In [11]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [12]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)

In [13]:
integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY), 1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)

In [14]:
onehot_encoded_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [15]:
#DC removal 
trainX -= (np.mean(trainX, axis=0) + 1e-8)
testX -= (np.mean(testX, axis=0) + 1e-8)

In [16]:
clf = keras.Sequential()

In [17]:
clf.add(keras.layers.Dense(
  units = 10,
  input_dim = trainX.shape[1],   
  activation = 'tanh'
))

clf.add(keras.layers.Dense(
    units = onehot_encoded_train.shape[1],
    input_dim = 10,
    activation = 'softmax'
))


In [18]:
onehot_encoded_train.shape[1],trainX.shape[1]

(2, 18)

In [19]:
clf.compile(loss='mean_squared_error',
    optimizer='Adam',
           metrics=['categorical_accuracy'])

In [20]:
history = clf.fit(trainX,onehot_encoded_train,
                 batch_size = 200, epochs = 150,
                 verbose = 1,
                 validation_split = 0.1)

Train on 640737 samples, validate on 71193 samples
Epoch 1/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.2148 - categorical_accuracy: 0.6886 - val_loss: 0.2156 - val_categorical_accuracy: 0.6856
Epoch 2/150
640737/640737 [==============================] - 3s 5us/step - loss: 0.2144 - categorical_accuracy: 0.6888 - val_loss: 0.2156 - val_categorical_accuracy: 0.6856
Epoch 3/150
640737/640737 [==============================] - 3s 5us/step - loss: 0.2144 - categorical_accuracy: 0.6888 - val_loss: 0.2156 - val_categorical_accuracy: 0.6856
Epoch 4/150
640737/640737 [==============================] - 3s 5us/step - loss: 0.2144 - categorical_accuracy: 0.6888 - val_loss: 0.2157 - val_categorical_accuracy: 0.6856
Epoch 5/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.2144 - categorical_accuracy: 0.6888 - val_loss: 0.2156 - val_categorical_accuracy: 0.6856
Epoch 6/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.2

Epoch 48/150
640737/640737 [==============================] - 5s 8us/step - loss: 0.2120 - categorical_accuracy: 0.6939 - val_loss: 0.2132 - val_categorical_accuracy: 0.6908
Epoch 49/150
640737/640737 [==============================] - 5s 7us/step - loss: 0.2119 - categorical_accuracy: 0.6939 - val_loss: 0.2130 - val_categorical_accuracy: 0.6911
Epoch 50/150
640737/640737 [==============================] - 5s 8us/step - loss: 0.2119 - categorical_accuracy: 0.6939 - val_loss: 0.2129 - val_categorical_accuracy: 0.6913
Epoch 51/150
640737/640737 [==============================] - 5s 8us/step - loss: 0.2118 - categorical_accuracy: 0.6939 - val_loss: 0.2129 - val_categorical_accuracy: 0.6910
Epoch 52/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.2118 - categorical_accuracy: 0.6938 - val_loss: 0.2129 - val_categorical_accuracy: 0.6909
Epoch 53/150
640737/640737 [==============================] - 4s 7us/step - loss: 0.2117 - categorical_accuracy: 0.6939 - val_loss

640737/640737 [==============================] - 6s 9us/step - loss: 0.1868 - categorical_accuracy: 0.7143 - val_loss: 0.1869 - val_categorical_accuracy: 0.7137
Epoch 96/150
640737/640737 [==============================] - 4s 7us/step - loss: 0.1857 - categorical_accuracy: 0.7153 - val_loss: 0.1864 - val_categorical_accuracy: 0.7103
Epoch 97/150
640737/640737 [==============================] - 4s 7us/step - loss: 0.1846 - categorical_accuracy: 0.7161 - val_loss: 0.1852 - val_categorical_accuracy: 0.7124
Epoch 98/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.1836 - categorical_accuracy: 0.7169 - val_loss: 0.1838 - val_categorical_accuracy: 0.7163
Epoch 99/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.1826 - categorical_accuracy: 0.7178 - val_loss: 0.1828 - val_categorical_accuracy: 0.7166
Epoch 100/150
640737/640737 [==============================] - 4s 7us/step - loss: 0.1817 - categorical_accuracy: 0.7187 - val_loss: 0.1819 - v

Epoch 142/150
640737/640737 [==============================] - 4s 7us/step - loss: 0.1644 - categorical_accuracy: 0.7440 - val_loss: 0.1651 - val_categorical_accuracy: 0.7427
Epoch 143/150
640737/640737 [==============================] - 5s 7us/step - loss: 0.1643 - categorical_accuracy: 0.7442 - val_loss: 0.1649 - val_categorical_accuracy: 0.7425
Epoch 144/150
640737/640737 [==============================] - 5s 7us/step - loss: 0.1642 - categorical_accuracy: 0.7441 - val_loss: 0.1652 - val_categorical_accuracy: 0.7412
Epoch 145/150
640737/640737 [==============================] - 4s 7us/step - loss: 0.1641 - categorical_accuracy: 0.7441 - val_loss: 0.1648 - val_categorical_accuracy: 0.7426
Epoch 146/150
640737/640737 [==============================] - 4s 6us/step - loss: 0.1640 - categorical_accuracy: 0.7443 - val_loss: 0.1646 - val_categorical_accuracy: 0.7434
Epoch 147/150
640737/640737 [==============================] - 5s 8us/step - loss: 0.1640 - categorical_accuracy: 0.7443 - va

In [21]:
testY[1:100], clf.predict_classes(testX[1:100,:])

(array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int64),
 array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64))

In [22]:
clf.evaluate(testX,onehot_encoded_test,verbose=0)

[0.16398050307153883, 0.7431215340754137]

In [25]:
clf_json = clf.to_json()
with open("NN_OwnVoice_108-10-2_inputs_bilBF.json", "w") as json_file:
    json_file.write(clf_json)
    
clf.save_weights("NN_OwnVoice_108-10-2_inputs_bilBF_weights.h5")

In [26]:
np.save('TestX_NN_OwnVoice_bilateral',testX), np.save('TestY_NN_OwnVoice_bilateral',testY),
np.save('OneHot_testY_bilateral',onehot_encoded_test)