In [1]:
#import necessary packages
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier 
import soundfile as sf

In [2]:
#import data 
path = '../Matlab code/'#'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=2NewNorm.wav')
classes = pd.read_csv(path + 'Classes_2NewNorm.csv')
#data = pd.read_csv(path + 'Data_EBR=2.csv')

In [3]:
X = data[:775361,:107]
Y = classes.values[:775361,0]


In [5]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [6]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)



In [7]:

integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY),1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)



In [9]:

onehot_encoded_train[1:10]

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [10]:
onehot_encoded_test[1:10]

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [11]:
#define neural net  108-18-4 
clf = MLPClassifier(hidden_layer_sizes=(18,),solver='adam',
                    activation='tanh',max_iter=500,verbose = True,
                    random_state=0,tol = 1e-4).fit(trainX,onehot_encoded_train)

Iteration 1, loss = 2.14840612
Iteration 2, loss = 2.12410813
Iteration 3, loss = 2.12403904
Iteration 4, loss = 2.12378716
Iteration 5, loss = 2.12227537
Iteration 6, loss = 2.11202884
Iteration 7, loss = 2.07072099
Iteration 8, loss = 1.99293601
Iteration 9, loss = 1.91056820
Iteration 10, loss = 1.84462783
Iteration 11, loss = 1.79869791
Iteration 12, loss = 1.76840510
Iteration 13, loss = 1.74844967
Iteration 14, loss = 1.73485199
Iteration 15, loss = 1.72506856
Iteration 16, loss = 1.71752958
Iteration 17, loss = 1.71140356
Iteration 18, loss = 1.70608767
Iteration 19, loss = 1.70112782
Iteration 20, loss = 1.69635009
Iteration 21, loss = 1.69154606
Iteration 22, loss = 1.68657804
Iteration 23, loss = 1.68135055
Iteration 24, loss = 1.67596595
Iteration 25, loss = 1.67038276
Iteration 26, loss = 1.66459151
Iteration 27, loss = 1.65864944
Iteration 28, loss = 1.65249097
Iteration 29, loss = 1.64623186
Iteration 30, loss = 1.63977633
Iteration 31, loss = 1.63320581
Iteration 32, los

Iteration 253, loss = 1.34275062
Iteration 254, loss = 1.34249781
Iteration 255, loss = 1.34225207
Iteration 256, loss = 1.34199472
Iteration 257, loss = 1.34182681
Iteration 258, loss = 1.34163866
Iteration 259, loss = 1.34142033
Iteration 260, loss = 1.34110968
Iteration 261, loss = 1.34068968
Iteration 262, loss = 1.34059376
Iteration 263, loss = 1.34038062
Iteration 264, loss = 1.34017449
Iteration 265, loss = 1.33995152
Iteration 266, loss = 1.33957347
Iteration 267, loss = 1.33928842
Iteration 268, loss = 1.33909716
Iteration 269, loss = 1.33889065
Iteration 270, loss = 1.33859316
Iteration 271, loss = 1.33838535
Iteration 272, loss = 1.33817935
Iteration 273, loss = 1.33788448
Iteration 274, loss = 1.33762148
Iteration 275, loss = 1.33755644
Iteration 276, loss = 1.33725109
Iteration 277, loss = 1.33694801
Iteration 278, loss = 1.33659658
Iteration 279, loss = 1.33651069
Iteration 280, loss = 1.33608423
Iteration 281, loss = 1.33584833
Iteration 282, loss = 1.33567658
Iteration 

c:\program files\python\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [13]:
clf.score(trainX,onehot_encoded_train)

0.5214481015270326

In [99]:
clf.score(testX,onehot_encoded_test)

0.7404512713367253

In [109]:
clf.classes_


array([0, 1, 2, 3])