In [1]:
#load packages
import numpy as np
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import soundfile as sf


In [2]:
#import data 
path = 'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=2.wav')
classes = pd.read_csv(path + 'Classes_2.csv')


In [3]:

X = data[:len(data)-1,:data.shape[1]] #775361
Y = classes.values[:,0]

In [4]:
Y

array([1, 1, 1, ..., 5, 5, 5], dtype=int64)

In [5]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [6]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)

In [7]:
integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY), 1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)


In [8]:
onehot_encoded_train 


array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [9]:
#DC removal 
trainX -= (np.mean(trainX, axis=0) + 1e-8)
testX -= (np.mean(testX, axis=0) + 1e-8)

In [10]:
clf = keras.Sequential()

In [11]:
onehot_encoded_train.shape[1], X.shape[1],onehot_encoded_train


(5, 108, array([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]]))

In [12]:
clf.add(keras.layers.Dense(
  units = 56,
  input_dim = trainX.shape[1],   
  activation = 'tanh'
))

clf.add(keras.layers.Dense(
    units = onehot_encoded_train.shape[1],
    input_dim = 56,
    activation = 'softmax'
))



In [13]:
onehot_encoded_train.shape[1]

5

In [14]:
clf.compile(loss='mean_squared_error',
    optimizer='Adam',
           metrics=['categorical_accuracy'])

In [15]:
history = clf.fit(trainX,onehot_encoded_train,
                 batch_size = 64, epochs = 150,
                 verbose = 1,
                 validation_split = 0.1)

Train on 698819 samples, validate on 77647 samples
Epoch 1/150
698819/698819 [==============================] - 17s 24us/step - loss: 0.1486 - categorical_accuracy: 0.3418 - val_loss: 0.1449 - val_categorical_accuracy: 0.3619
Epoch 2/150
698819/698819 [==============================] - 16s 22us/step - loss: 0.1435 - categorical_accuracy: 0.3880 - val_loss: 0.1420 - val_categorical_accuracy: 0.4086
Epoch 3/150
698819/698819 [==============================] - 15s 22us/step - loss: 0.1405 - categorical_accuracy: 0.4219 - val_loss: 0.1384 - val_categorical_accuracy: 0.4457
Epoch 4/150
698819/698819 [==============================] - 14s 20us/step - loss: 0.1373 - categorical_accuracy: 0.4507 - val_loss: 0.1361 - val_categorical_accuracy: 0.4606
Epoch 5/150
698819/698819 [==============================] - 15s 22us/step - loss: 0.1356 - categorical_accuracy: 0.4687 - val_loss: 0.1345 - val_categorical_accuracy: 0.4781
Epoch 6/150
698819/698819 [==============================] - 14s 20us/step

698819/698819 [==============================] - 15s 22us/step - loss: 0.0764 - categorical_accuracy: 0.7217 - val_loss: 0.0760 - val_categorical_accuracy: 0.7338
Epoch 48/150
698819/698819 [==============================] - 13s 19us/step - loss: 0.0760 - categorical_accuracy: 0.7238 - val_loss: 0.0756 - val_categorical_accuracy: 0.7330
Epoch 49/150
698819/698819 [==============================] - 13s 18us/step - loss: 0.0756 - categorical_accuracy: 0.7256 - val_loss: 0.0756 - val_categorical_accuracy: 0.7280
Epoch 50/150
698819/698819 [==============================] - 15s 21us/step - loss: 0.0752 - categorical_accuracy: 0.7282 - val_loss: 0.0749 - val_categorical_accuracy: 0.7314
Epoch 51/150
698819/698819 [==============================] - 14s 20us/step - loss: 0.0749 - categorical_accuracy: 0.7294 - val_loss: 0.0750 - val_categorical_accuracy: 0.7125
Epoch 52/150
698819/698819 [==============================] - 18s 26us/step - loss: 0.0745 - categorical_accuracy: 0.7320 - val_loss:

698819/698819 [==============================] - 12s 17us/step - loss: 0.0609 - categorical_accuracy: 0.7916 - val_loss: 0.0611 - val_categorical_accuracy: 0.7865
Epoch 94/150
698819/698819 [==============================] - 12s 17us/step - loss: 0.0607 - categorical_accuracy: 0.7924 - val_loss: 0.0609 - val_categorical_accuracy: 0.7867
Epoch 95/150
698819/698819 [==============================] - 11s 16us/step - loss: 0.0605 - categorical_accuracy: 0.7931 - val_loss: 0.0606 - val_categorical_accuracy: 0.7934
Epoch 96/150
698819/698819 [==============================] - 15s 21us/step - loss: 0.0603 - categorical_accuracy: 0.7940 - val_loss: 0.0604 - val_categorical_accuracy: 0.7914
Epoch 97/150
698819/698819 [==============================] - 12s 17us/step - loss: 0.0601 - categorical_accuracy: 0.7944 - val_loss: 0.0600 - val_categorical_accuracy: 0.7967
Epoch 98/150
698819/698819 [==============================] - 11s 16us/step - loss: 0.0599 - categorical_accuracy: 0.7955 - val_loss:

698819/698819 [==============================] - 13s 18us/step - loss: 0.0545 - categorical_accuracy: 0.8159 - val_loss: 0.0548 - val_categorical_accuracy: 0.8177
Epoch 140/150
698819/698819 [==============================] - 13s 18us/step - loss: 0.0544 - categorical_accuracy: 0.8163 - val_loss: 0.0548 - val_categorical_accuracy: 0.8100
Epoch 141/150
698819/698819 [==============================] - 14s 19us/step - loss: 0.0543 - categorical_accuracy: 0.8166 - val_loss: 0.0545 - val_categorical_accuracy: 0.8187
Epoch 142/150
698819/698819 [==============================] - 11s 16us/step - loss: 0.0542 - categorical_accuracy: 0.8167 - val_loss: 0.0542 - val_categorical_accuracy: 0.8173
Epoch 143/150
698819/698819 [==============================] - 11s 16us/step - loss: 0.0541 - categorical_accuracy: 0.8172 - val_loss: 0.0541 - val_categorical_accuracy: 0.8168
Epoch 144/150
698819/698819 [==============================] - 11s 16us/step - loss: 0.0540 - categorical_accuracy: 0.8176 - val_

In [17]:
clf.predict_classes(testX[1:100,:]) + 1,testY[1:100]

(array([2, 4, 1, 5, 2, 4, 4, 2, 4, 1, 3, 2, 3, 1, 3, 3, 2, 4, 3, 4, 2, 4,
        5, 2, 5, 4, 2, 2, 2, 2, 5, 2, 4, 1, 4, 4, 2, 2, 5, 2, 4, 2, 5, 3,
        1, 3, 5, 4, 3, 2, 2, 5, 1, 5, 5, 2, 5, 4, 2, 2, 2, 4, 5, 2, 2, 1,
        2, 2, 1, 2, 2, 1, 1, 2, 1, 5, 3, 4, 5, 2, 3, 5, 2, 5, 2, 2, 2, 2,
        5, 4, 5, 4, 4, 2, 4, 4, 2, 1, 1], dtype=int64),
 array([2, 5, 1, 5, 2, 4, 4, 2, 4, 4, 3, 2, 3, 1, 3, 3, 2, 4, 3, 4, 2, 4,
        4, 2, 5, 5, 4, 5, 2, 4, 5, 4, 4, 1, 5, 4, 2, 2, 5, 2, 4, 4, 5, 3,
        1, 3, 5, 5, 3, 2, 4, 5, 1, 5, 5, 4, 5, 4, 4, 2, 2, 2, 1, 4, 2, 1,
        2, 2, 1, 4, 2, 1, 4, 2, 1, 5, 3, 4, 5, 4, 3, 5, 2, 5, 4, 2, 2, 2,
        4, 5, 5, 4, 4, 2, 4, 5, 2, 1, 1], dtype=int64))

In [18]:
clf.evaluate(testX,onehot_encoded_test,verbose=1)

194117/194117 [==============================] - 3s 16us/step


[0.053336052134293536, 0.8198612177195176]

In [19]:
# saving the model 
# save model and weights
clf_json = clf.to_json()
with open("NN_108-56-5.json", "w") as json_file:
    json_file.write(clf_json)
    
clf.save_weights("NN_108-56-5_weights.h5")

In [20]:
np.save('TestX_NN_108-56-5',testX), np.save('TestY_NN_108-56-5',testY),
np.save('OneHot_testY_108-56-5',onehot_encoded_test)