In [1]:
#load packages
import numpy as np
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import soundfile as sf
import os
import h5py

In [2]:
#import data 
path = 'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=2_uni_OwnVoice.wav')
classes = pd.read_csv(path + 'Classes_2_uni_OwnVoice.csv')

In [3]:
X = data[:len(data)-1,:data.shape[1]] 
Y = classes.values[:,0]

In [4]:
len(Y),len(X)

(366756, 366756)

In [5]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [6]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)

In [7]:
integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY), 1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)

In [8]:
onehot_encoded_train

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [9]:
#DC removal 
trainX -= (np.mean(trainX, axis=0) + 1e-8)
testX -= (np.mean(testX, axis=0) + 1e-8)

In [10]:
clf = keras.Sequential()

In [11]:
clf.add(keras.layers.Dense(
  units = 20,
  input_dim = trainX.shape[1],   
  activation = 'tanh'
))

clf.add(keras.layers.Dense(
    units = onehot_encoded_train.shape[1],
    input_dim = 20,
    activation = 'softmax'
))


In [12]:
onehot_encoded_train.shape[1],trainX.shape[1]

(4, 36)

In [13]:
clf.compile(loss='mean_squared_error',
    optimizer='Adam',
           metrics=['categorical_accuracy'])

In [15]:
history = clf.fit(trainX,onehot_encoded_train,
                 batch_size = 200, epochs = 250,
                 verbose = 1,
                 validation_split = 0.1)

Train on 264063 samples, validate on 29341 samples
Epoch 1/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1696 - categorical_accuracy: 0.3825 - val_loss: 0.1695 - val_categorical_accuracy: 0.3859
Epoch 2/250
264063/264063 [==============================] - 2s 7us/step - loss: 0.1694 - categorical_accuracy: 0.3829 - val_loss: 0.1694 - val_categorical_accuracy: 0.3832
Epoch 3/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1692 - categorical_accuracy: 0.3842 - val_loss: 0.1692 - val_categorical_accuracy: 0.3835
Epoch 4/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1690 - categorical_accuracy: 0.3859 - val_loss: 0.1691 - val_categorical_accuracy: 0.3943
Epoch 5/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1688 - categorical_accuracy: 0.3871 - val_loss: 0.1688 - val_categorical_accuracy: 0.3889
Epoch 6/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1

Epoch 48/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1606 - categorical_accuracy: 0.4352 - val_loss: 0.1608 - val_categorical_accuracy: 0.4366
Epoch 49/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1605 - categorical_accuracy: 0.4368 - val_loss: 0.1607 - val_categorical_accuracy: 0.4517
Epoch 50/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1603 - categorical_accuracy: 0.4377 - val_loss: 0.1606 - val_categorical_accuracy: 0.4393
Epoch 51/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1602 - categorical_accuracy: 0.4384 - val_loss: 0.1604 - val_categorical_accuracy: 0.4440
Epoch 52/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1601 - categorical_accuracy: 0.4385 - val_loss: 0.1603 - val_categorical_accuracy: 0.4463
Epoch 53/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1599 - categorical_accuracy: 0.4407 - val_loss

264063/264063 [==============================] - 1s 4us/step - loss: 0.1552 - categorical_accuracy: 0.4694 - val_loss: 0.1557 - val_categorical_accuracy: 0.4549
Epoch 96/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1551 - categorical_accuracy: 0.4695 - val_loss: 0.1554 - val_categorical_accuracy: 0.4645
Epoch 97/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1550 - categorical_accuracy: 0.4710 - val_loss: 0.1552 - val_categorical_accuracy: 0.4718
Epoch 98/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1549 - categorical_accuracy: 0.4704 - val_loss: 0.1551 - val_categorical_accuracy: 0.4768
Epoch 99/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1548 - categorical_accuracy: 0.4705 - val_loss: 0.1550 - val_categorical_accuracy: 0.4796
Epoch 100/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1547 - categorical_accuracy: 0.4706 - val_loss: 0.1551 - v

Epoch 142/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1508 - categorical_accuracy: 0.4899 - val_loss: 0.1510 - val_categorical_accuracy: 0.4841
Epoch 143/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1507 - categorical_accuracy: 0.4888 - val_loss: 0.1508 - val_categorical_accuracy: 0.4967
Epoch 144/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1506 - categorical_accuracy: 0.4896 - val_loss: 0.1508 - val_categorical_accuracy: 0.4930
Epoch 145/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1505 - categorical_accuracy: 0.4913 - val_loss: 0.1507 - val_categorical_accuracy: 0.4885
Epoch 146/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1504 - categorical_accuracy: 0.4910 - val_loss: 0.1505 - val_categorical_accuracy: 0.4986
Epoch 147/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1504 - categorical_accuracy: 0.4908 - va

Epoch 189/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1473 - categorical_accuracy: 0.5039 - val_loss: 0.1476 - val_categorical_accuracy: 0.5069
Epoch 190/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1472 - categorical_accuracy: 0.5048 - val_loss: 0.1474 - val_categorical_accuracy: 0.5115
Epoch 191/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1472 - categorical_accuracy: 0.5046 - val_loss: 0.1475 - val_categorical_accuracy: 0.5045
Epoch 192/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1471 - categorical_accuracy: 0.5049 - val_loss: 0.1474 - val_categorical_accuracy: 0.5056
Epoch 193/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1471 - categorical_accuracy: 0.5055 - val_loss: 0.1475 - val_categorical_accuracy: 0.5024
Epoch 194/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1470 - categorical_accuracy: 0.5055 - va

Epoch 236/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1453 - categorical_accuracy: 0.5122 - val_loss: 0.1454 - val_categorical_accuracy: 0.5174
Epoch 237/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1452 - categorical_accuracy: 0.5120 - val_loss: 0.1455 - val_categorical_accuracy: 0.5086
Epoch 238/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1452 - categorical_accuracy: 0.5126 - val_loss: 0.1454 - val_categorical_accuracy: 0.5167
Epoch 239/250
264063/264063 [==============================] - 1s 4us/step - loss: 0.1452 - categorical_accuracy: 0.5116 - val_loss: 0.1453 - val_categorical_accuracy: 0.5170
Epoch 240/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1451 - categorical_accuracy: 0.5129 - val_loss: 0.1453 - val_categorical_accuracy: 0.5177
Epoch 241/250
264063/264063 [==============================] - 1s 5us/step - loss: 0.1451 - categorical_accuracy: 0.5118 - va

In [19]:

testY[1:100]-1, clf.predict_classes(testX[1:100,:])

(array([1, 2, 3, 3, 1, 2, 1, 3, 1, 0, 0, 1, 2, 2, 1, 2, 3, 2, 0, 1, 3, 2,
        0, 2, 2, 1, 1, 3, 3, 0, 2, 3, 3, 3, 0, 0, 3, 1, 0, 1, 2, 1, 3, 2,
        1, 3, 2, 3, 1, 2, 2, 3, 1, 2, 1, 2, 1, 2, 3, 0, 0, 2, 1, 1, 1, 3,
        0, 2, 1, 3, 1, 3, 1, 1, 3, 0, 1, 2, 1, 3, 0, 3, 2, 1, 3, 2, 3, 0,
        3, 0, 0, 0, 2, 1, 3, 1, 0, 3, 1], dtype=int64),
 array([2, 2, 3, 3, 3, 2, 1, 3, 1, 0, 1, 2, 2, 2, 2, 1, 3, 3, 2, 2, 3, 2,
        2, 2, 2, 2, 3, 3, 3, 0, 3, 3, 2, 3, 2, 3, 2, 2, 2, 3, 2, 2, 3, 1,
        2, 2, 2, 3, 1, 2, 2, 3, 1, 3, 2, 2, 3, 0, 2, 3, 0, 2, 0, 1, 1, 3,
        3, 3, 2, 3, 2, 3, 3, 2, 3, 2, 1, 2, 2, 3, 2, 3, 3, 1, 3, 3, 3, 0,
        3, 1, 0, 3, 2, 3, 2, 2, 2, 3, 1], dtype=int64))

In [20]:
clf.evaluate(testX,onehot_encoded_test,verbose=1)

73352/73352 [==============================] - 1s 9us/step


[0.14520121206112888, 0.5158686879703348]

In [21]:
# save model and weights
clf_json = clf.to_json()
with open("NN_OwnVoice_36-20-4_inputs_uniBF.json", "w") as json_file:
    json_file.write(clf_json)
    
clf.save_weights("NN_OwnVoice_36-20-4_inputs_uniBF_weights.h5")

In [22]:
np.save('TestX_NN_OwnVoice_uniBF_separation',testX), np.save('TestY_NN_OwnVoice_uniBF_separation',testY),
np.save('OneHot_testY_uniBF_separation',onehot_encoded_test)

In [23]:
clf.evaluate(testX,onehot_encoded_test,verbose=1)

73352/73352 [==============================] - 1s 8us/step


[0.14520121206112888, 0.5158686879703348]

In [38]:
h5py.run_tests()

.....................................................x...............................s...................................x....................................s...s......ss.ss..............................................................................ss....................ssssss...................................................................x....x.........................x......x.................................................ssss..................
----------------------------------------------------------------------
Ran 457 tests in 2.785s

OK (skipped=19, expected failures=6)


<unittest.runner.TextTestResult run=457 errors=0 failures=0>

In [44]:
history.params


{'batch_size': 200,
 'epochs': 150,
 'steps': None,
 'samples': 640737,
 'verbose': 1,
 'do_validation': True,
 'metrics': ['loss',
  'categorical_accuracy',
  'val_loss',
  'val_categorical_accuracy']}