In [1]:
#load packages
import numpy as np
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import soundfile as sf


In [2]:
#import data 
path = 'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=2.wav')
classes = pd.read_csv(path + 'Classes_2.csv')


In [3]:
# front left and front right as predictors
X = data[:len(data)-1,0*18:1*18] 
Y = classes.values[:,0]

In [4]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [5]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)

In [6]:
integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY), 1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)


In [7]:
onehot_encoded_train 


array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [8]:
#DC removal 
trainX -= (np.mean(trainX, axis=0) + 1e-8)
testX -= (np.mean(testX, axis=0) + 1e-8)

In [9]:
clf = keras.Sequential()

In [10]:
onehot_encoded_train.shape[1], X.shape[1],onehot_encoded_train


(5, 18, array([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]]))

In [11]:
clf.add(keras.layers.Dense(
  units = 12,
  input_dim = trainX.shape[1],   
  activation = 'tanh'
))

clf.add(keras.layers.Dense(
    units = onehot_encoded_train.shape[1],
    input_dim = 12,
    activation = 'softmax'
))



In [12]:
onehot_encoded_train.shape[1]

5

In [13]:
clf.compile(loss='mean_squared_error',
    optimizer='Adam',
           metrics=['categorical_accuracy'])

In [14]:
history = clf.fit(trainX,onehot_encoded_train,
                 batch_size = 64, epochs = 150,
                 verbose = 1,
                 validation_split = 0.1)

Train on 698819 samples, validate on 77647 samples
Epoch 1/150
698819/698819 [==============================] - 8s 12us/step - loss: 0.1542 - categorical_accuracy: 0.2856 - val_loss: 0.1541 - val_categorical_accuracy: 0.2780
Epoch 2/150
698819/698819 [==============================] - 8s 11us/step - loss: 0.1533 - categorical_accuracy: 0.3016 - val_loss: 0.1511 - val_categorical_accuracy: 0.3296
Epoch 3/150
698819/698819 [==============================] - 8s 11us/step - loss: 0.1515 - categorical_accuracy: 0.3295 - val_loss: 0.1509 - val_categorical_accuracy: 0.3338
Epoch 4/150
698819/698819 [==============================] - 8s 11us/step - loss: 0.1513 - categorical_accuracy: 0.3335 - val_loss: 0.1507 - val_categorical_accuracy: 0.3401
Epoch 5/150
698819/698819 [==============================] - 8s 11us/step - loss: 0.1510 - categorical_accuracy: 0.3401 - val_loss: 0.1503 - val_categorical_accuracy: 0.3336
Epoch 6/150
698819/698819 [==============================] - 8s 12us/step - los

698819/698819 [==============================] - 7s 10us/step - loss: 0.1247 - categorical_accuracy: 0.5007 - val_loss: 0.1243 - val_categorical_accuracy: 0.5036
Epoch 48/150
698819/698819 [==============================] - 7s 11us/step - loss: 0.1243 - categorical_accuracy: 0.5021 - val_loss: 0.1241 - val_categorical_accuracy: 0.5068
Epoch 49/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1239 - categorical_accuracy: 0.5034 - val_loss: 0.1236 - val_categorical_accuracy: 0.5030
Epoch 50/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1236 - categorical_accuracy: 0.5042 - val_loss: 0.1236 - val_categorical_accuracy: 0.5095
Epoch 51/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1234 - categorical_accuracy: 0.5051 - val_loss: 0.1232 - val_categorical_accuracy: 0.4983
Epoch 52/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1231 - categorical_accuracy: 0.5056 - val_loss: 0.122

Epoch 94/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1196 - categorical_accuracy: 0.5040 - val_loss: 0.1197 - val_categorical_accuracy: 0.4759
Epoch 95/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1195 - categorical_accuracy: 0.5038 - val_loss: 0.1194 - val_categorical_accuracy: 0.5004
Epoch 96/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1195 - categorical_accuracy: 0.5037 - val_loss: 0.1194 - val_categorical_accuracy: 0.5056
Epoch 97/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1195 - categorical_accuracy: 0.5038 - val_loss: 0.1195 - val_categorical_accuracy: 0.5128
Epoch 98/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1194 - categorical_accuracy: 0.5035 - val_loss: 0.1193 - val_categorical_accuracy: 0.4963
Epoch 99/150
698819/698819 [==============================] - 7s 10us/step - loss: 0.1194 - categorical_accuracy: 0.5038 - va

698819/698819 [==============================] - 11s 15us/step - loss: 0.1183 - categorical_accuracy: 0.5015 - val_loss: 0.1182 - val_categorical_accuracy: 0.5110
Epoch 141/150
698819/698819 [==============================] - 8s 12us/step - loss: 0.1183 - categorical_accuracy: 0.5012 - val_loss: 0.1182 - val_categorical_accuracy: 0.5095
Epoch 142/150
698819/698819 [==============================] - 8s 12us/step - loss: 0.1182 - categorical_accuracy: 0.5013 - val_loss: 0.1180 - val_categorical_accuracy: 0.4966
Epoch 143/150
698819/698819 [==============================] - 8s 12us/step - loss: 0.1182 - categorical_accuracy: 0.5015 - val_loss: 0.1179 - val_categorical_accuracy: 0.4998
Epoch 144/150
698819/698819 [==============================] - 9s 12us/step - loss: 0.1181 - categorical_accuracy: 0.5019 - val_loss: 0.1182 - val_categorical_accuracy: 0.4930
Epoch 145/150
698819/698819 [==============================] - 8s 12us/step - loss: 0.1181 - categorical_accuracy: 0.5016 - val_loss:

In [50]:
clf.predict_classes(testX[1:100,:]) + 1,testY[1:100]

(array([2, 4, 2, 5, 2, 1, 1, 2, 4, 2, 3, 2, 3, 4, 3, 3, 2, 2, 3, 4, 2, 4,
        5, 2, 5, 4, 2, 2, 2, 2, 5, 2, 2, 1, 4, 4, 2, 2, 1, 2, 4, 2, 5, 3,
        2, 3, 5, 4, 3, 2, 2, 5, 4, 5, 2, 4, 4, 2, 2, 2, 2, 4, 3, 4, 2, 2,
        2, 2, 1, 2, 2, 1, 1, 2, 4, 5, 3, 4, 5, 2, 5, 5, 2, 5, 2, 2, 2, 2,
        5, 5, 2, 4, 4, 2, 4, 4, 2, 1, 1], dtype=int64),
 array([2, 5, 1, 5, 2, 4, 4, 2, 4, 4, 3, 2, 3, 1, 3, 3, 2, 4, 3, 4, 2, 4,
        4, 2, 5, 5, 4, 5, 2, 4, 5, 4, 4, 1, 5, 4, 2, 2, 5, 2, 4, 4, 5, 3,
        1, 3, 5, 5, 3, 2, 4, 5, 1, 5, 5, 4, 5, 4, 4, 2, 2, 2, 1, 4, 2, 1,
        2, 2, 1, 4, 2, 1, 4, 2, 1, 5, 3, 4, 5, 4, 3, 5, 2, 5, 4, 2, 2, 2,
        4, 5, 5, 4, 4, 2, 4, 5, 2, 1, 1], dtype=int64))

In [51]:
clf.evaluate(testX,onehot_encoded_test,verbose=1)

194117/194117 [==============================] - 2s 10us/step


[0.08945091667563816, 0.6597206839180454]

In [52]:
# saving the model 
# save model and weights
clf_json = clf.to_json()
with open("NN_18-12-5.json", "w") as json_file:
    json_file.write(clf_json)
    
clf.save_weights("NN_18-12-5_weights.h5")

In [53]:
np.save('TestX_NN_18-12-5',testX), np.save('TestY_NN_18-12-5',testY),
np.save('OneHot_testY_18-12-5',onehot_encoded_test)