In [1]:
#load packages
import numpy as np
import tensorflow as tf
from tensorflow import keras 
import pandas as pd
import soundfile as sf


In [2]:
#import data 
path = 'x:/Steering/Recordings/Processed/'
data, fs = sf.read(path + 'ERB=1.wav')
classes = pd.read_csv(path + 'Classes_1.csv')

In [3]:
X = data[:len(data)-1,:data.shape[1]] #775361
Y = classes.values[:,0]

In [4]:
#split into training and test set
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(X,Y,test_size=0.2,random_state=0)

In [5]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

enc = OneHotEncoder(sparse=False)

In [6]:
integer_encoded_train = trainY.reshape(len(trainY), 1)
onehot_encoded_train = enc.fit_transform(integer_encoded_train)

integer_encoded_test = testY.reshape(len(testY), 1)
onehot_encoded_test = enc.fit_transform(integer_encoded_test)

In [7]:
onehot_encoded_train 


array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [8]:
#DC removal 
trainX -= (np.mean(trainX, axis=0) + 1e-8)
testX -= (np.mean(testX, axis=0) + 1e-8)

In [9]:
clf = keras.Sequential()

In [10]:
onehot_encoded_train.shape[1], X.shape[1],onehot_encoded_train

(5, 216, array([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.]]))

In [11]:
clf.add(keras.layers.Dense(
  units = 110,
  input_dim = trainX.shape[1],   
  activation = 'tanh'
))

clf.add(keras.layers.Dense(
    units = onehot_encoded_train.shape[1],
    input_dim = 110,
    activation = 'softmax'
))


In [12]:
onehot_encoded_train.shape[1]

5

In [13]:
clf.compile(loss='mean_squared_error',
    optimizer='Adam',
           metrics=['categorical_accuracy'])

In [14]:
history = clf.fit(trainX,onehot_encoded_train,
                 batch_size = 100, epochs = 150,
                 verbose = 1,
                 validation_split = 0.1)

Train on 763214 samples, validate on 84802 samples
Epoch 1/150
763214/763214 [==============================] - 14s 18us/step - loss: 0.1411 - categorical_accuracy: 0.4344 - val_loss: 0.1368 - val_categorical_accuracy: 0.4594
Epoch 2/150
763214/763214 [==============================] - 13s 16us/step - loss: 0.1359 - categorical_accuracy: 0.4659 - val_loss: 0.1352 - val_categorical_accuracy: 0.4682
Epoch 3/150
763214/763214 [==============================] - 11s 15us/step - loss: 0.1345 - categorical_accuracy: 0.4709 - val_loss: 0.1340 - val_categorical_accuracy: 0.4724
Epoch 4/150
763214/763214 [==============================] - 12s 16us/step - loss: 0.1333 - categorical_accuracy: 0.4720 - val_loss: 0.1332 - val_categorical_accuracy: 0.4738
Epoch 5/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.1306 - categorical_accuracy: 0.4772 - val_loss: 0.1286 - val_categorical_accuracy: 0.4730
Epoch 6/150
763214/763214 [==============================] - 12s 16us/step

763214/763214 [==============================] - 12s 16us/step - loss: 0.0623 - categorical_accuracy: 0.7852 - val_loss: 0.0622 - val_categorical_accuracy: 0.7832
Epoch 48/150
763214/763214 [==============================] - 15s 20us/step - loss: 0.0616 - categorical_accuracy: 0.7885 - val_loss: 0.0609 - val_categorical_accuracy: 0.7895
Epoch 49/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0609 - categorical_accuracy: 0.7913 - val_loss: 0.0605 - val_categorical_accuracy: 0.7974
Epoch 50/150
763214/763214 [==============================] - 14s 18us/step - loss: 0.0602 - categorical_accuracy: 0.7941 - val_loss: 0.0599 - val_categorical_accuracy: 0.7944
Epoch 51/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0596 - categorical_accuracy: 0.7969 - val_loss: 0.0596 - val_categorical_accuracy: 0.7943
Epoch 52/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0589 - categorical_accuracy: 0.7993 - val_loss:

763214/763214 [==============================] - 15s 20us/step - loss: 0.0430 - categorical_accuracy: 0.8598 - val_loss: 0.0432 - val_categorical_accuracy: 0.8609
Epoch 94/150
763214/763214 [==============================] - 13s 16us/step - loss: 0.0428 - categorical_accuracy: 0.8604 - val_loss: 0.0427 - val_categorical_accuracy: 0.8596
Epoch 95/150
763214/763214 [==============================] - 13s 17us/step - loss: 0.0426 - categorical_accuracy: 0.8610 - val_loss: 0.0428 - val_categorical_accuracy: 0.8608
Epoch 96/150
763214/763214 [==============================] - 14s 18us/step - loss: 0.0424 - categorical_accuracy: 0.8618 - val_loss: 0.0427 - val_categorical_accuracy: 0.8609
Epoch 97/150
763214/763214 [==============================] - 19s 25us/step - loss: 0.0423 - categorical_accuracy: 0.8622 - val_loss: 0.0423 - val_categorical_accuracy: 0.8621
Epoch 98/150
763214/763214 [==============================] - 18s 23us/step - loss: 0.0421 - categorical_accuracy: 0.8631 - val_loss:

763214/763214 [==============================] - 37s 48us/step - loss: 0.0372 - categorical_accuracy: 0.8799 - val_loss: 0.0375 - val_categorical_accuracy: 0.8796
Epoch 140/150
763214/763214 [==============================] - 19s 24us/step - loss: 0.0371 - categorical_accuracy: 0.8800 - val_loss: 0.0376 - val_categorical_accuracy: 0.8787
Epoch 141/150
763214/763214 [==============================] - 18s 24us/step - loss: 0.0370 - categorical_accuracy: 0.8805 - val_loss: 0.0377 - val_categorical_accuracy: 0.8794
Epoch 142/150
763214/763214 [==============================] - 36s 47us/step - loss: 0.0369 - categorical_accuracy: 0.8807 - val_loss: 0.0372 - val_categorical_accuracy: 0.8798
Epoch 143/150
763214/763214 [==============================] - 22s 29us/step - loss: 0.0368 - categorical_accuracy: 0.8810 - val_loss: 0.0369 - val_categorical_accuracy: 0.8798
Epoch 144/150
763214/763214 [==============================] - 19s 24us/step - loss: 0.0367 - categorical_accuracy: 0.8813 - val_

In [15]:
data.shape[1]    

216

In [16]:
clf.predict_classes(testX[:100,:]) + 1,testY[:100]

(array([4, 4, 2, 3, 3, 2, 1, 4, 2, 5, 3, 1, 2, 3, 2, 4, 4, 2, 1, 4, 2, 4,
        2, 2, 2, 2, 2, 1, 4, 5, 2, 3, 5, 4, 2, 2, 4, 3, 3, 3, 4, 1, 2, 2,
        2, 1, 4, 2, 3, 4, 4, 4, 2, 2, 4, 4, 3, 5, 1, 4, 3, 1, 5, 2, 4, 3,
        5, 2, 5, 4, 2, 1, 4, 5, 2, 4, 2, 3, 4, 2, 1, 2, 2, 5, 3, 2, 5, 4,
        4, 1, 2, 4, 2, 2, 1, 4, 4, 5, 4, 1], dtype=int64),
 array([4, 4, 4, 3, 3, 2, 1, 4, 2, 5, 3, 4, 2, 3, 2, 5, 4, 2, 1, 5, 2, 4,
        2, 2, 2, 2, 4, 1, 4, 5, 4, 3, 5, 4, 4, 2, 4, 3, 3, 3, 4, 1, 2, 2,
        2, 1, 4, 2, 3, 5, 5, 4, 2, 2, 4, 2, 3, 5, 1, 4, 3, 1, 5, 2, 5, 3,
        4, 2, 4, 4, 2, 1, 4, 4, 4, 4, 2, 3, 4, 2, 1, 2, 2, 5, 3, 4, 5, 2,
        4, 1, 2, 4, 4, 2, 1, 4, 4, 5, 4, 4], dtype=int64))

In [17]:
testY[:100]

array([4, 4, 4, 3, 3, 2, 1, 4, 2, 5, 3, 4, 2, 3, 2, 5, 4, 2, 1, 5, 2, 4,
       2, 2, 2, 2, 4, 1, 4, 5, 4, 3, 5, 4, 4, 2, 4, 3, 3, 3, 4, 1, 2, 2,
       2, 1, 4, 2, 3, 5, 5, 4, 2, 2, 4, 2, 3, 5, 1, 4, 3, 1, 5, 2, 5, 3,
       4, 2, 4, 4, 2, 1, 4, 4, 4, 4, 2, 3, 4, 2, 1, 2, 2, 5, 3, 4, 5, 2,
       4, 1, 2, 4, 4, 2, 1, 4, 4, 5, 4, 4], dtype=int64)

In [18]:
# saving the model 
# save model and weights
clf_json = clf.to_json()
with open("NN_216-110-5.json", "w") as json_file:
    json_file.write(clf_json)
    
clf.save_weights("NN_216-110-5_weights.h5")

In [19]:
np.save('TestX_NN_216-110-5',testX), np.save('TestY_NN_216-110-5',testY),
np.save('OneHot_testY_216-110-5',onehot_encoded_test)