In [1]:
#import packages
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [2]:
#load test vector from training set
path = '../../Recordings/Processed/'
train_test = pd.read_csv(path + 'TrainingSet_DoubleERB.csv')

In [3]:
pca = PCA(n_components = 9) #after some trial and error I chose the number of components to 9; 
#cut-off is at 1% contribution to variance

In [4]:
trainX = train_test.values[:,0:107]
trainY = train_test.values[:,108]

In [5]:
clf = pca.fit(trainX)

In [6]:
clf.explained_variance_ratio_

array([0.33642321, 0.24009197, 0.14775241, 0.08640801, 0.06515276,
       0.04656699, 0.02600989, 0.02081131, 0.01648572])

In [7]:
pca_values = clf.transform(trainX)


In [8]:
#do one-hot encoding
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

In [9]:
enc = OneHotEncoder(sparse=False)
lab = LabelEncoder()

In [10]:
integer_encoded = trainY
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)


In [11]:
onehot_encoded = enc.fit_transform(integer_encoded)


In [12]:
onehot_encoded

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [13]:
pca_train = np.column_stack([pca_values,onehot_encoded])

In [14]:
np.savetxt('pca_train_data.csv',pca_train,delimiter=',')

In [15]:
trainY

array([1., 1., 1., ..., 4., 4., 4.])